services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - microservices

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      # Interaction with Microservices
      - "5672:5672"
      # Management Console Port
      - "15672:15672"
    networks:
      - microservices

  service-discovery:
    image: michaelxsteinertxcontainer/service-discovery:latest
    container_name: service-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8761:8761"
    networks:
      - microservices
    depends_on:
      - zipkin

  api-gateway:
    image: michaelxsteinertxcontainer/api-gateway:latest
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8083:8083"
    networks:
      - microservices
    depends_on:
      - service-discovery
      - zipkin

  customer:
    image: michaelxsteinertxcontainer/customer:latest
    container_name: customer
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    networks:
      - postgres
      - microservices
    depends_on:
      - service-discovery
      - zipkin
      - postgres
      - rabbitmq

  fraud:
    image: michaelxsteinertxcontainer/fraud:latest
    container_name: fraud
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8081"
    networks:
      - postgres
      - microservices
    depends_on:
      - service-discovery
      - zipkin
      - postgres
      - rabbitmq

  notification:
    image: michaelxsteinertxcontainer/notification:latest
    container_name: notification
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8082:8082"
    networks:
      - postgres
      - microservices
    depends_on:
      - service-discovery
      - zipkin
      - postgres
      - rabbitmq

networks:
  postgres:
    driver: bridge
  microservices:
    driver: bridge

volumes:
  postgres:
  pgadmin: